[env]
TERM = "xterm-256color"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "none"
startup_mode = "maximized"
opacity = 0.95

[font]
size = 11

[window.padding]
x = 20
y = 20

[colors.primary]
background = "#1e1e1e"
foreground = "#abb2bf"

[colors.normal]
black = "#1e1e1e"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.bright]
black = "#3f3f3f"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#bfc5ce"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#3e4452"

