[env]
TERM = "xterm-256color"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "none"
startup_mode = "maximized"
opacity = 1

[font]
size = 11

[window.padding]
x = 20
y = 20

# Colors (Doom One)
[colors.primary]
background = "0x282c34"
foreground = "0xbbc2cf"

[colors.normal]
black = "0x282c34"
red = "0xff6c6b"
green = "0x98be65"
yellow = "0xecbe7b"
blue = "0x51afef"
magenta = "0xc678dd"
cyan = "0x46d9ff"
white = "0xbbc2cf"
