[env]
TERM = "xterm-256color"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font]
size = 13

[shell]
args = ["-d Debian", "--cd", "/mnt/c/Users/nokk/Workspace"]
program = 'C:\Windows\System32\wsl.exe'

[window]
decorations = "none"
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[colors.primary]
background = "0x282c34"

foreground = "0xbbc2cf"

[colors.normal]
black = "0x282c34"

red = "0xff6c6b"
green = "0x98be65"
yellow = "0xecbe7b"
blue = "0x51afef"
magenta = "0xc678dd"
cyan = "0x46d9ff"
white = "0xbbc2cf"
